# HTTP redirect
server {
    listen      80 default_server reuseport;
    listen      [::]:80 default_server reuseport;
    server_name _;
    include     nginxconfig.io/zerossl.conf;
    # include     nginxconfig.io/limit.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}
